### ISSUE TITLE
可以构建一个 1.0.1 的 Mac 版吗？

### ISSUE THREAD

**Issue by DiamondYuan** [ririv/QuickOutline#5]

**Comment by ririv** [comment]
可以，但也许得要过个几天，因为mac版只能在mac中构建，之前我是用的虚拟机，但是由于上次电脑出现了致命问题重装了系统后，虚拟机也就跟着没了。我后面几天正打算换一台mac电脑，到时候帮你构建，构建好了我还会回复此issue

**Comment by meetpython** [comment]
坐等一个Mac版～求求了

**Comment by meetpython** [comment]
非常感谢这个工具，我把我几百本没目录的书都配置好了，很感谢🙏有几个小建议：
1.复制粘贴目录的文本后，每次点击自动缩进，文本输入光标都会回到行首，而需要从行尾操作的话，每次都需要下拉菜单至行尾，一旦目录的文本特别长的话，很不方便，能否自动缩进后，默认输入光标移至行尾；
2.有好几本电子书（异步社区购买，扫描版，扫描质量很好），原有目录有很多错误和偏移量不对，我就删除了整个目录，重新设置，但出现了中文文本乱码的问题（会不会因为原有书籍的文本格式就是有问题的……）；
3.我自己是一个 Android / iOS 的开发者，技术栈是 Flutter 为主，也会使用 SwiftUI，另外也很擅长使用 Electron 构建桌面软件，不知作者是否有兴趣为这款工具更换颜值更高的 GUI（对不起🧎‍♀️，不是刻意要吐槽 GUI 不好看的～）。我可以用 Electron 做一个颜值更高的 GUI。
4.会不会有 Linux 的桌面版本～

**Comment by ririv** [comment]
> 非常感谢这个工具，我把我几百本没目录的书都配置好了，很感谢🙏有几个小建议： 1.复制粘贴目录的文本后，每次点击自动缩进，文本输入光标都会回到行首，而需要从行尾操作的话，每次都需要下拉菜单至行尾，一旦目录的文本特别长的话，很不方便，能否自动缩进后，默认输入光标移至行尾； 2.有好几本电子书（异步社区购买，扫描版，扫描质量很好），原有目录有很多错误和偏移量不对，我就删除了整个目录，重新设置，但出现了中文文本乱码的问题（会不会因为原有书籍的文本格式就是有问题的……）； 3.我自己是一个 Android / iOS 的开发者，技术栈是 Flutter 为主，也会使用 SwiftUI，另外也很擅长使用 Electron 构建桌面软件，不知作者是否有兴趣为这款工具更换颜值更高的 GUI（对不起🧎‍♀️，不是刻意要吐槽 GUI 不好看的～）。我可以用 Electron 做一个颜值更高的 GUI。 4.会不会有 Linux 的桌面版本～

1. 这个需求是可以的
2. 目前我并没有遇到中文乱码问题，所以我也不知道什么原因
3. 我本来的确想用js做个更好看的界面，但奈何java自带的webview太差了，而使用Electron会导致体积膨胀，这本来就是一个基于java的项目，可以看到只是一个小工具，软件体积就很大了，要是再使用Electron的话，体积又会更大，我觉得这只是一个小工具，就光现在的体积我已经很不满意了，所以就没有用Electron，至于你说的界面美化，我也一直有考虑，奈何javafx并没有非常好的UI库，之前看到jb发开的kotlin的UI库Jetpack Compose for Desktop，有想换的想法，可惜这是个新项目，我那个时间看的时候连1.0都没有出（现在看了下好像刚出1.0）
4. 可以有Linux版本，因为java是全平台的，只要在linux中打包一下就行

另外我最近由于期末考试加很多的大作业要做，有点忙，等到考完了我还会继续优化，并把mac版弄好的

**Comment by ririv** [comment]
> 非常感谢这个工具，我把我几百本没目录的书都配置好了，很感谢🙏有几个小建议： 1.复制粘贴目录的文本后，每次点击自动缩进，文本输入光标都会回到行首，而需要从行尾操作的话，每次都需要下拉菜单至行尾，一旦目录的文本特别长的话，很不方便，能否自动缩进后，默认输入光标移至行尾； 2.有好几本电子书（异步社区购买，扫描版，扫描质量很好），原有目录有很多错误和偏移量不对，我就删除了整个目录，重新设置，但出现了中文文本乱码的问题（会不会因为原有书籍的文本格式就是有问题的……）； 3.我自己是一个 Android / iOS 的开发者，技术栈是 Flutter 为主，也会使用 SwiftUI，另外也很擅长使用 Electron 构建桌面软件，不知作者是否有兴趣为这款工具更换颜值更高的 GUI（对不起🧎‍♀️，不是刻意要吐槽 GUI 不好看的～）。我可以用 Electron 做一个颜值更高的 GUI。 4.会不会有 Linux 的桌面版本～



等考完试我会研究下1.0版本的Jetpack Compose for Desktop，如果可用的话，我会把UI库换成它，javafx的确不是一个好的选择，当然如果你有更好的UI建议，也可以告诉我，但至于Electron，我想暂时因为两者结合体积太大的原因并不会考虑。另外你了解flutter，不知道使用java+flutter的方式会不会是一个更好的选择呢，flutter应该是可以与java通信的

**Comment by ririv** [comment]
macos版已构建
